# Generated by Django 3.2.4 on 2021-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0039_auto_20210823_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isPrimary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_short_desc',
            field=models.TextField(blank=True, verbose_name='Короткое описание для Schema'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_slug',
            field=models.CharField(default='article2021-09-20 14:33:47.152465', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_slug',
            field=models.CharField(default='slug2021-09-20 14:33:47.124464', max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_slug',
            field=models.CharField(default='region2021-09-20 14:33:47.153058', max_length=200, verbose_name='URL'),
        ),
    ]
